// `npm run evidence` — regenerate every public number from live sources and
// the ledger, write the raw artifacts, and rebuild METRICS.md from them. No
// model. Any figure quoted in the README or the submission form must appear in
// METRICS.md, and every line of METRICS.md names the artifact it came from.
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { BudgetGuard } from "../src/pipeline/budget.js";
import { rwaContracts } from "../src/lib/bitget/rest.js";
import { gatherEvidence } from "../src/desk/evidence.js";
import { closeSignalMcp, signalStatus } from "../src/lib/bitget/signal.js";
import { scoreboard, resolveDue } from "../src/desk/ledger.js";
import { usCashSession } from "../src/lib/bitget/session.js";

const DIR = "artifacts";
mkdirSync(DIR, { recursive: true });
const budget = new BudgetGuard();
const stamp = new Date().toISOString();
const write = (name: string, data: unknown) => {
  writeFileSync(`${DIR}/${name}`, JSON.stringify(data, null, 2) + "\n");
  return `${DIR}/${name}`;
};

// 1. The rToken universe, discovered — not hardcoded.
const universe = await rwaContracts(budget);
const universeFile = write("rwa-universe.json", { at: stamp, count: universe.length, symbols: universe.map((c) => c.symbol).sort() });

// 2. The evidence table for three names: a mega-cap, an index, and one the desk should call quiet.
const tables: Record<string, string> = {};
for (const [t, name] of [["NVDA", "NVIDIA"], ["SPY", "SPDR S&P 500"], ["KO", "Coca-Cola"]] as const) {
  const ev = await gatherEvidence(`evidence snapshot for ${t}`, t, name, budget);
  tables[t] = write(`evidence-${t}.json`, ev);
}

// 3. The Skill service, as seen right now.
const signal = await signalStatus();
const signalFile = write("bitget-signal-status.json", { at: stamp, ...signal });

// 4. The ledger, graded, and its chain.
await resolveDue().catch(() => 0);
const board = scoreboard(1000);
const boardFile = write("scoreboard.json", { at: stamp, ...board });

// 5. The offline suite — the count comes from running it, not from a claim.
let testLine = "not run";
try {
  const out = execSync("npm test 2>&1", { encoding: "utf8", env: { ...process.env, DATABASE_PATH: "./data/test.db" } });
  const m = out.match(/tests (\d+)[\s\S]*?pass (\d+)[\s\S]*?fail (\d+)/);
  testLine = m ? `${m[2]}/${m[1]} pass, ${m[3]} fail` : "could not parse";
  writeFileSync(`${DIR}/tests.txt`, out);
} catch (err) {
  testLine = `suite failed: ${String(err).slice(0, 80)}`;
}

const ev = (t: string) => JSON.parse(readFileSync(tables[t], "utf8"));
const cov = (t: string) => ev(t).coverage;
const gap = (t: string) => ev(t).gap ?? {};
const git = (() => { try { return execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim(); } catch { return "uncommitted"; } })();

const md = `# METRICS

Regenerated by \`npm run evidence\` at ${stamp} (commit ${git}). Every number below names the artifact it was read from; the artifacts are committed under \`${DIR}/\`. Figures are **observed** unless marked otherwise.

## Coverage of the tradable universe
- rToken perpetuals discovered on Bitget (\`isRwa\`, status normal): **${universe.length}** — \`${universeFile}\`
- US cash session at snapshot: **${usCashSession()}**

## Evidence tables (no model; $0.0000)
| ticker | rows ok / total | computed ok | coverage | perp | cash | perp vs cash | basis | funding / yr | artifact |
|---|---|---|---|---|---|---|---|---|---|
${["NVDA", "SPY", "KO"].map((t) => `| ${t} | ${cov(t).ok}/${cov(t).total} | ${cov(t).computed_ok} | ${cov(t).ratio} | ${gap(t).perp_price ?? "—"} | ${gap(t).cash_price ?? "—"} | ${gap(t).perp_vs_cash_pct ?? "—"}% | ${gap(t).basis_pct ?? "—"}% | ${gap(t).funding_annualized_pct ?? "—"}% | \`${tables[t]}\` |`).join("\n")}

Rows that report \`error\` are third-party upstreams that did not answer; the desk names them rather than filling them in.

## bitget-signal (perception layer) at snapshot
- connected: **${signal.connected}** · tools listed: **${signal.tools.length}** — \`${signalFile}\`
- Bitget-backed tools (ticker cross-check, technicals) answered; tools that reach external upstreams (news, earnings, macro, sentiment) reported blank errors during the build week — see the per-row status in the evidence artifacts.

## Scoreboard (the usage record)
- reads: **${board.summary.reads}** · debated: **${board.summary.debated}** · abstained: **${board.summary.abstained}** · graded: **${board.summary.graded}**
- hit rate: **${board.summary.hit_rate ?? "— (nothing resolved yet)"}** · mean Brier: **${board.summary.mean_brier ?? "—"}** · Brier Index: **${board.summary.brier_index ?? "—"}**
- ledger chain: **${board.chain.valid ? "valid" : "BROKEN"}** over ${board.chain.rows} rows, head \`${board.chain.head ?? "—"}\` — \`${boardFile}\`
- calibration buckets: ${board.summary.calibration.length ? board.summary.calibration.map((b) => `${b.bucket}: n=${b.n}, said ${Math.round(b.mean_p * 100)}%, held ${Math.round(b.hit_rate * 100)}%`).join("; ") : "none resolved yet"}

## Tests
- offline suite: **${testLine}** — \`${DIR}/tests.txt\`

## What has NOT been observed
- The debate and judge path requires a model key; reads on this ledger with \`call = none\` were produced in degraded mode (computed evidence, no verdict) and are never graded. **Targeted** for the competition window: ≥ 20 debated reads across ≥ 5 tickers, graded at horizon, with the calibration table populated.
- Platt scaling (post-hoc recalibration) is **planned**, not applied: it needs a resolved sample first.
`;
writeFileSync("METRICS.md", md);
console.log(md);
console.log(`cost: $${budget.total().toFixed(4)}`);
await closeSignalMcp();
process.exit(0);
